import { Poppins } from "next/font/google";
import './globals.css';
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";
import CalendlyContextProvider from "./CalendlyContext";
import CalendlyModal from "@/components/calendlyModal";
import MobileMenuContextProvider from "./MobileMenuContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--poppins",
});

export const metadata = {
  title: "Eva Perlay - Coaching, Traning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <CalendlyContextProvider>
          <MobileMenuContextProvider>
          <body className={`${poppins.variable} text-poppins bg-[--white]`}>
            <Navbar />
              {children}
            <Footer />
            <CalendlyModal />
          </body>
          </MobileMenuContextProvider>
        </CalendlyContextProvider>
    </html>
  );
}
